name: Publish VTunit docker image
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - feature/setup_using_git_version
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish vtunit
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vtunr/vtunit
          dockerfile: docker/Dockerfile
          tag_with_sha: true
          tag_with_ref: true
          tags: latest
          
      - name: Publish vtunit_esp
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vtunr/vtunit_esp
          dockerfile: docker/esp/Dockerfile
          tag_with_sha: true
          tag_with_ref: true
          tags: latest