name: Publish VTunit docker image
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - master

jobs:
  publish_vtunit_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish vtunit
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: vtunr/vtunit
          dockerfile: docker/Dockerfile
          tag_with_sha: true
          tag_with_ref: true
          tags: latest
   
  publish_vtunit_docker_esp:  
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        sdk_version: ["v4.0", "v4.2"]
    steps:        
      - name: Set Environment Variables
        run: |
          echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}   
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Publish vtunit_esp
        uses: docker/build-push-action@v2
        with:      
          build-args: |
            ESP_SDK_VERSION=${{matrix.sdk_version}}
          push: true
          repository: vtunr/vtunit_esp
          file: docker/esp/Dockerfile
          tags: | 
            vtunr/vtunit_esp:sha-${{ env.GIT_SHA }}_${{matrix.sdk_version}}
            vtunr/vtunit_esp:latest_${{matrix.sdk_version}}